google_analytics_id: G-X0BJ20T7XR

hero_image: assets/img/flowers.jpg
hero_position: center center
# mobile_hero_image: assets/img/bell.jpg
# mobile_hero_position: center center

theme:
  # text_color: '#404040'
  primary_color: '#d98560'
  # secondary_color: '#a2a183'
  # accent_color: '#afa63d'
  # background_color: '#ffff'

rsvp:
  use_code: true
  code: 1234
  code_md5: 81dc9bdb52d04dc20036dbd8313ed055
    # the thing it's redeirected to
    # post_address: https://script.googleusercontent.com/macros/echo?user_content_key=BBJlVeeZ0L21PptF4h02g2klDwKe7NYbQffwAHjW_VXjllwXNeYK09PELo749ZR70ndwfahb_uiEX-wVorSi47ns8ank_Vhcm5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnAv41CuTLxL1rIReKRSdkDeF4NtTdfHQ1ph2gjGV4SW6Lck-5DPsf6I_XFoFNaq0wyjziCxDyiH5stArsW0ObI6jxXkXI52iKQ&amp;lib=ME_FxXc335GKym-kAkCIdzXGe0gmIaYGN
    #post_address: https://script.google.com/macros/s/AKfycbzh1EbS-IkwuCpeipbYGUDplpx5VneVqhmv0EFtmAA_Xzyfyj6OtnykOT1i5Z91XyPS/exec
  post_address: https://script.google.com/macros/s/AKfycbzy8pB3kZlMqaZfJ6eL2ZsJ2_abLRujiOXO3iHQbQuo8hzYllZrKpz49Gn06ZjZN9hW/exec
    # api_key: m7ccqIIa6S8uSBQzbhZzd1rZaoiCXObr1fcx4Wvy
    # code_location: You can put the code on the back of your RSVP card, or turn off this functionality all together. The code for this sample is 1234
  yes_text: I'll be there
  no_text: I can't make it
  no_extra_guests_message: As much as we would love to have everyone, please only include guests that were listed on your invitation
  submit_text: RSVP
  cancel_text: Cancel
  yes_modal_title: Thank You!
  no_modal_title: Thank You!
  yes_modal_body: We're glad that you're hanging out with us on our wedding day!
  no_modal_body: We really wish you could have made it, but we still love you. <span class="fa fa-heart"></span>
  sms_followup_text: You'll receive a text confirmation shortly.

  # Comment these out to disable
  song_text: What songs will get you dancing?
  leave_a_message_text: Please list any dietary restrictions or anything else you think we should know!

people:
  families_header: Our Families
  families_text: We would be nothing if it wasn't for the love and support of our wonderful parents and siblings.
  kids_header: Little Ones
  kids_text: We're so lucky to have our sweet puppies help us celebrate the big day.
  wedding_party_header: Wedding Party
